---
# tasks file for install_jenkins
- name: Download and install Required Dependencies
  yum:
    name:
      - wget
      - java-1.8.0-openjdk

- name: Download jenkins Repo
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: "{{ jenkins_repo_dest }}"

- name: Import Jenkins RPM Key
  rpm_key:
    state: present
    key: "{{ jenkins_rpm_key }}"

- name: Install Jenkins
  yum:
    state: present
    name: jenkins

- name: Start Jenkins for the first time
  service:
    name: jenkins
    state: started
    enabled: yes
  notify:
    - Get Jenkins password
    - Print Jenkins password
    
